FRUITS_CLASS = [
    "Apple Braeburn",
    "Apple Crimson Snow",
    "Apple Golden 1",
    "Apple Golden 2",
    "Apple Golden 3",
    "Apple Granny Smith",
    "Apple Pink Lady",
    "Apple Red 1",
    "Apple Red 2",
    "Apple Red 3",
    "Apple Red Delicious",
    "Apple Red Yellow 1",
    "Apple Red Yellow 2",
    "Apricot",
    "Avocado",
    "Avocado ripe",
    "Banana",
    "Banana Lady Finger",
    "Banana Red",
    "Beetroot",
    "Blueberry",
    "Cactus fruit",
    "Cantaloupe 1",
    "Cantaloupe 2",
    "Carambula",
    "Cauliflower",
    "Cherry 1",
    "Cherry 2",
    "Cherry Rainier",
    "Cherry Wax Black",
    "Cherry Wax Red",
    "Cherry Wax Yellow",
    "Chestnut",
    "Clementine",
    "Cocos",
    "Corn",
    "Corn Husk",
    "Cucumber Ripe",
    "Cucumber Ripe 2",
    "Dates",
    "Eggplant",
    "Fig",
    "Ginger Root",
    "Granadilla",
    "Grape Blue",
    "Grape Pink",
    "Grape White",
    "Grape White 2",
    "Grape White 3",
    "Grape White 4",
    "Grapefruit Pink",
    "Grapefruit White",
    "Guava",
    "Huckleberry",
    "Kaki",
    "Kiwi",
    "Kohlrabi",
    "Kumquats",
    "Lemon",
    "Lemon Meyer",
    "Limes",
    "Lychee",
    "Mandarine",
    "Mango",
    "Mango Red",
    "Mangostan",
    "Maracuja",
    "Melon Piel de Sapo",
    "Mulberry",
    "Nectarine",
    "Nectarine Flat",
    "Nut Forest",
    "Nut Pecan",
    "Onion Red",
    "Onion Red Peeled",
    "Onion White",
    "Orange",
    "Papaya",
    "Passion Fruit",
    "Peach",
    "Peach 2",
    "Peach Flat",
    "Pear",
    "Pear Abate",
    "Pear Forelle",
    "Pear Kaiser",
    "Pear Monster",
    "Pear Red",
    "Pear Stone",
    "Pear Williams",
    "Pepino",
    "Pepper Green",
    "Pepper Orange",
    "Pepper Red",
    "Pepper Yellow",
    "Physalis",
    "Physalis with Husk",
    "Pineapple",
    "Pineapple Mini",
    "Pitahaya Red",
    "Plum",
    "Plum 2",
    "Plum 3",
    "Pomegranate",
    "Potato Red",
    "Potato Red Washed",
    "Potato Sweet",
    "Potato White",
    "Quince",
    "Rambutan",
    "Raspberry",
    "Redcurrant",
    "Salak",
    "Strawberry",
    "Strawberry Wedge",
    "Tamarillo",
    "Tangelo",
    "Tomato 1",
    "Tomato 2",
    "Tomato 3",
    "Tomato 4",
    "Tomato Cherry Red",
    "Tomato Heart",
    "Tomato Maroon",
    "Tomato not Ripened",
    "Tomato Yellow",
    "Walnut",
    "Watermelon"
]

FRUIT_NUTRITION_INFO = {
    "Apple": {"calories": 52, "vitC": "4.6mg", "fiber": "2.4g", "desc": "giàu Vitamin C và chất xơ"},
    "Apricot": {"calories": 48, "vitC": "10mg", "fiber": "2g", "desc": "giàu Vitamin A và Kali"},
    "Avocado": {"calories": 160, "vitC": "10mg", "fiber": "6.7g", "desc": "giàu chất béo lành mạnh và Kali"},
    "Banana": {"calories": 89, "vitC": "8.7mg", "fiber": "2.6g", "desc": "giàu Kali và năng lượng"},
    "Blueberry": {"calories": 57, "vitC": "9.7mg", "fiber": "2.4g", "desc": "siêu chống oxy hóa"},
    "Cherry": {"calories": 50, "vitC": "7mg", "fiber": "1.6g", "desc": "giàu anthocyanin"},
    "Grape": {"calories": 69, "vitC": "3.2mg", "fiber": "0.9g", "desc": "giàu resveratrol"},
    "Kiwi": {"calories": 61, "vitC": "92.7mg", "fiber": "3g", "desc": "cực giàu Vitamin C"},
    "Lemon": {"calories": 29, "vitC": "53mg", "fiber": "2.8g", "desc": "giàu Vitamin C và axit citric"},
    "Mango": {"calories": 60, "vitC": "36.4mg", "fiber": "1.6g", "desc": "giàu Vitamin A và C"},
    "Orange": {"calories": 47, "vitC": "53mg", "fiber": "2.4g", "desc": "siêu giàu Vitamin C"},
    "Peach": {"calories": 39, "vitC": "6.6mg", "fiber": "1.5g", "desc": "giàu Vitamin A"},
    "Pear": {"calories": 57, "vitC": "4.3mg", "fiber": "3.1g", "desc": "giàu chất xơ và Kali"},
    "Pineapple": {"calories": 50, "vitC": "47.8mg", "fiber": "1.4g", "desc": "giàu bromelain và Vitamin C"},
    "Strawberry": {"calories": 32, "vitC": "58.8mg", "fiber": "2g", "desc": "giàu Vitamin C và chống oxy hóa"},
    "Watermelon": {"calories": 30, "vitC": "8.1mg", "fiber": "0.4g", "desc": "giàu nước và lycopene"},
    "Default": {"calories": "chưa xác định", "vitC": "không rõ", "fiber": "không rõ", "desc": "thông tin dinh dưỡng chưa có"}
}


FRUITS_DATA = []
for fruit_name in FRUITS_CLASS:
    key = fruit_name.split()[0]  # lấy từ đầu để match với FRUIT_NUTRITION_INFO
    nutrition = FRUIT_NUTRITION_INFO.get(key, FRUIT_NUTRITION_INFO["Default"])
    FRUITS_DATA.append({
        "name": fruit_name,
        "nutrition": nutrition
    })
